# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "some"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["tily"]
  s.date = "2013-04-06"
  s.description = "sumo clone for NIFTY Cloud"
  s.email = "tidnlyam@gmail.com"
  s.executables = ["some"]
  s.extra_rdoc_files = [
    "README.md",
    "TODO"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/some",
    "lib/some.rb",
    "spec/base.rb",
    "spec/some_spec.rb"
  ]
  s.homepage = "http://github.com/tily/some"
  s.require_paths = ["lib"]
  s.rubyforge_project = "some"
  s.rubygems_version = "1.8.13"
  s.summary = "sumo clone for NIFTY Cloud"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nifty-cloud-sdk>, ["= 1.11.beta1"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
    else
      s.add_dependency(%q<nifty-cloud-sdk>, ["= 1.11.beta1"])
      s.add_dependency(%q<thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<nifty-cloud-sdk>, ["= 1.11.beta1"])
    s.add_dependency(%q<thor>, [">= 0"])
  end
end

